# Generated by Django 2.2.13 on 2020-06-15 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='nama',
            field=models.CharField(default='tes', max_length=50),
            preserve_default=False,
        ),
    ]
