# Generated by Django 2.2.13 on 2020-06-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImage', '0002_auto_20200615_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='Image2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='upload',
            name='Image3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='Image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
